# Generated by Django 3.1.1 on 2020-10-27 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_watchlists',
            field=models.ManyToManyField(blank=True, related_name='following', to='main.Watchlist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_watchlist', to='main.watchlist'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
