# Generated by Django 3.1.1 on 2020-10-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201027_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='followers',
        ),
    ]
