# Generated by Django 3.1.1 on 2020-12-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_watchlist_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimTickers',
            fields=[
                ('ticker_name', models.TextField(primary_key=True, serialize=False)),
                ('category', models.TextField(blank=True, null=True)),
                ('ticker_type', models.TextField(blank=True, null=True)),
                ('exchange', models.TextField(blank=True, null=True)),
                ('num_contracts', models.IntegerField(blank=True, null=True)),
                ('leverage_ratio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_tickers',
                'managed': False,
            },
        ),
    ]
