# Generated by Django 3.1.1 on 2020-12-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201205_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etfdailyquote',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='futuresdailyquote',
            options={'managed': False},
        ),
    ]
