# Generated by Django 3.1.1 on 2020-12-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201206_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='exchange',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='leverage_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='num_contracts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='etfdailyquote',
            table='fct_etf_daily',
        ),
        migrations.AlterModelTable(
            name='futuresdailyquote',
            table='fct_futures_daily',
        ),
    ]
